sudo: true
language: java
jdk:
  #- openjdk6 TODO: For some reason, JDK6 fails on Javadoc on the new container infrastructure.
  # That's why we have to run it on the old infrastructure for now
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  include:
    - jdk: openjdk6
      sudo: true
install: gradle setupCIWorkspace
script: gradle build
notifications:
  email: false
